version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=urlshortcut
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  lb:
    build:
      context: .
      dockerfile: DockerfileLB
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/urlshortcut
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=password
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: lb
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/urlshortcut
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=password
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: shortcut
    depends_on:
      - db
      - lb